### ISSUE TITLE
no English version?

### ISSUE THREAD

**Issue by jeffreys-cat** [mehrabisajad/ng2-datetimepicker-jalali#1]
I found this component from npm.com, but it seems just has native language version.I don't know how to use it.

**Comment by mehrabisajad** [comment]
You can use the `bootstrap` component for the English version. And combine their components together. 

 https://github.com/ng-bootstrap/ng-bootstrap

Or get the code and remove the following from file `datetimepicker.component.ts`.
https://github.com/mehrabisajad/ng2-datetimepicker-jalali/blob/e6b3b965c991501af7ef8b7bcfaa8061cf5b54f1/src/datetimepicker.component.ts#L39-L40

**Comment by jeffreys-cat** [comment]
get it, thanks!
